apiVersion: v1
data:
  config_map_key1: value1
  config_map_key2: value2
  GREETING: ktal
  DATABASE_HOST: mysql-service
  DATABASE_PORT: '3306'
  DATABASE_PASSWORD: test1234
  DATABASE_USER: root
  DATABASE_SCHEMA: name
kind: ConfigMap
metadata:
  name: example-config