kind: Deployment
apiVersion: apps/v1
metadata:
  name: react-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-react-app
  template:
    metadata:
      labels:
        app: my-react-app
    spec:
      containers:
        - name: my-react-app-frontend
          image: quay.io/plopezpe/kube-app-frontend
          ports:
            - containerPort: 3000
      restartPolicy: Always
